title: AI Platform Presentation
logo: /Images/CloudMachineLearning.png
description: Data Science Processes with the Google Cloud AI-Platform as an example
show_downloads: false
#google_analytics:
theme: jekyll-theme-minimal