bucket: ml-productive-pipeline-12345
credentials: cred/service_acccount_123.json
env-name: gcp_dl
pkg-name: pkg_mnist_fnn
project-id: ml-productive-pipeline-12345
region: europe-west1
testdatafile: data/mnist/json/ml_engine_testdatafile_N4.json
tf-version: '1.13'
