channels:
- defaults
- conda-forge
dependencies:
- python=3.6
- numpy=1.14
- scipy=1.1
- scikit-learn=0.20
- tornado
- jupyter
- jupyterlab
- jupyter_contrib_nbextensions
- jupyter_nbextensions_configurator
- pandas=0.23
- matplotlib
#- nomkl # Only for Mac user
- notebook
- ipykernel
- ipywidgets
- nbconvert
- tensorflow=1.13
- tensorboard=1.13
- watermark
- pytest=3.6
- autopep8
- pylint
- pep8=1.7
- pylama=7.4
- nbdime
- pip=18
- google-auth
- pillow
- oauth2client
- google-api-python-client
- google-cloud-bigquery
- google-cloud-storage
