channels:
- defaults
- conda-forge
dependencies:
- python=3.6.6
#- numpy=1.14.5
#- scipy=1.1.0
#- scikit-learn=0.20.1
- tornado=4.5.3
- jupyter=1.0.0
- jupyterlab=0.34.9
- jupyter_contrib_nbextensions=0.5.0
- jupyter_nbextensions_configurator=0.4.0
#- pandas=0.23.4
#- matplotlib=3.0.2
#- nomkl # Only for Mac user
- notebook=5.6.0
- ipykernel=4.10.0
- ipywidgets=7.4.1
- nbconvert=5.4.0
#- tensorflow=1.12.0
#- tensorboard=1.12.0
#- watermark
#- pytest=3.6.2
- autopep8
- pylint
- pep8=1.7.1
- pylama=7.4.3
- nbdime
- pip=18.0
- pip:
  #- tf-nightly-2.0-preview
  - tfds-nightly
  #- tf-nightly-2.0-preview==2.0.0.dev20190207
  #- tf-nightly-2.0-preview==2.0.0.dev20190208
  - tf-nightly-2.0-preview==2.0.0.dev20190212
  #- tensorflow==1.13.0rc0
  #- tensorflow-estimator==1.13.0rc0
